# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Distinct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='Title')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.City', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Distinct',
                'verbose_name_plural': 'Distincts',
            },
        ),
    ]
