# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='distinct',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
