# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_auto_20180129_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Distinct',
            new_name='District',
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
    ]
